{% set version = "v0.1.5" %}

package:
    name: faampy
    version: {{ version }}

source:
    fn: faampy-{{ version }}.tar.gz
    url: https://github.com/ncasuk/faampy/archive/{{ version }}.tar.gz
    sha256: 65c9803d6ae127f244a54864cacb9c36d899d9640d35ede0054e8d7026f88de4

build:
    skip: True  # [py3k]
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - basemap
        - cartopy
        - configparser
        - ephem
        - matplotlib >=1.4.0
        - netcdf4 >=1.0
        - numpy
        - scipy
        - pandas
        - exifread
        - fiona
        - georaster
        - haversine
        - pillow
        - libspatialite
        - seaborn
        - simplekml
        - sqlite ==3.13.0
        - xarray

test:
    imports:
        - faampy

about:
    home: http://www.faam.ac.uk
    license: LGPLv3
    license_file: COPYING
    summary: 'FAAM aircraft data processing module'

extra:
    recipe-maintainers:
        - awellpott
